services:
  tx-consumer-db:
    image: postgres:18.4-alpine
    restart: on-failure
    networks:
      - net
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: tx-consumer
      POSTGRES_USER: tx-consumer
      POSTGRES_PASSWORD: tx-consumer
    healthcheck:
      test: [ CMD-SHELL, 'pg_isready -U tx-consumer -d tx-consumer' ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - tx-consumer:/var/lib/postgresql

  kafka-broker:
    image: apache/kafka:4.3.1
    restart: on-failure
    networks:
      - net
    ports:
      - '9092:19092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,CLIENT_EXPOSED:PLAINTEXT,BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: CLIENT://:9092,CLIENT_EXPOSED://:19092,BROKER://:19093,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka-broker:9092,CLIENT_EXPOSED://localhost:9092,BROKER://kafka-broker:19093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: [ CMD-SHELL, '/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092' ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - kafka-broker-data:/var/lib/kafka/data

  kafka-topics-init:
    image: apache/kafka:4.3.1
    restart: no
    networks:
      - net
    depends_on:
      kafka-broker:
        condition: service_healthy
    environment:
      KAFKA_INIT_TOPICS_BOOTSTRAP_SERVER: kafka-broker:9092
    volumes:
      - ./scripts/create-topics.sh:/scripts/create-topics.sh:ro
    entrypoint: [ /bin/sh, /scripts/create-topics.sh ]

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.5.0
    restart: on-failure
    networks:
      - net
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9092

volumes:
  tx-consumer:
  kafka-broker-data:

networks:
  net: